### PR TITLE
Fix chmod mode bug

### PR DESCRIPTION
**Pull request by wiktor2200**
Solve #4

:bell: This PR has potentially braking changes, because I've renamed: `nextcloud_backup_mode` variable to `nextcloud_backup_file_mode` for files and `nextcloud_backup_dir_mode` for directories.

### CODE REVIEW

**Comment by wiktor2200** [comment]
This PR should be merged after #1

**Review by aalaesar — CHANGES_REQUESTED** [review]
even after having merged #1 i still see the same commits that make the PR bigger than it should. could you rebase the branch and cleanup the duplicate commits ? thank you 😃

**Comment by wiktor2200** [comment]
@aalaesar done :)

**Review by aalaesar — CHANGES_REQUESTED** [review]
I had to use my time machine to fix the mess done by my gitea mirror. and I also deleted the test folder from History. please rebase (again) your branch please.
I'm not sure but you may need to discard the old commit history from master first
sorry 😞

**Comment by wiktor2200** [comment]
Fixed as well :)

**Comment by wiktor2200** [comment]
I hope, that's all. This PR should be merged first and then I'll resolve conflicts for others (if occurs).

**Comment by aalaesar** [comment]
there still [this commit](https://github.com/aalaesar/backup_nextcloud/pull/5/commits/9c1eb517a892a572dba7584e93043d5a8ace989f)  in the commit history I would like to remove if you don't mind 😃

**Comment by wiktor2200** [comment]
I've finally fixed it, I had to clean my branch. :)

**Review by aalaesar — APPROVED** [review]

**Pull request merged**
